import { removeManagedSkill, syncManagedSkill } from './managed-skills'

export const AGENT_SKILL_NAME = 'lodestar-agent'

const NO_FURTHER_AGENTS = [
  'Complete this task yourself. You must not create or invoke any further Agents or subagents.',
  'This includes Lodestar delegation, provider-native Agent/subagent tools, and delegation through CLIs or HTTP APIs.',
]

export const DELEGATED_AGENT_INSTRUCTIONS = [
  'You are a delegated Agent working on a task assigned by the main Agent.',
  ...NO_FURTHER_AGENTS,
  'If additional Agent work is needed, report the need to the main Agent so it can assign that work.',
].join('\n')

export const PROJECT_AGENT_INSTRUCTIONS = [
  'You are executing an independent project task owned by Lodestar. There is no parent main Agent.',
  ...NO_FURTHER_AGENTS,
  'If additional Agent work is needed, report the need to the caller.',
].join('\n')

export function agentSkillBody(): string {
  const description = 'Lodestar Agent calls: main Agents must bind calls to their managed session; independent services and applications must bind calls to a project. Resume unique native session IDs only within the same project and group. Delegated Agents and subagents must not delegate further.'
  return [
    '---',
    `name: ${AGENT_SKILL_NAME}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '# lodestar-agent',
    '',
    'Use Lodestar to call the Agent represented by a selected live identity.',
    'Each identity resolves to its configured Token Source, provider Agent backend,',
    'model, and effort. The caller-supplied prompt becomes that Agent run\'s task.',
    '',
    '## 调用归属（强制）',
    '',
    '| 调用场景 | 必须使用的绑定 |',
    '| --- | --- |',
    '| Agent 正在执行用户任务，需要调用另一个 Agent / 模型辅助执行 | 绑定当前会话：使用普通 `lodestar-agent` 命令，不传 `--project` |',
    '| 独立服务、定时任务或其他软件直接调用 | 绑定项目：每个命令都显式传 `--project <项目名>` |',
    '',
    '- Agent 通过 Shell、Python、脚本或 HTTP 发起的调用仍然属于 Agent 执行任务，必须绑定会话。',
    '- 不得把当前任务中的调用包装成“外部服务”，不得清除会话环境变量、复制项目凭据或使用 `--project` 脱离会话生命周期。',
    '- 没有有效会话上下文时，Agent 调用必须报错；项目入口不是会话凭据缺失、过期或失败时的替代路径。',
    '- 独立服务和软件不借用任何主 Agent 的会话凭据，统一使用项目入口。项目任务有自己的卡片和取消入口，不依赖主会话存活。',
    '',
    '## 会话 ID 与恢复范围（强制）',
    '',
    '- `session_id`（JSON 的 `workers[].session_id`）是原生会话的唯一 ID，续跑保持不变。',
    '- `run_id` 只标识某一次调用记录，不是另一个会话 ID；不要为绑定方式或续跑创建第二套会话标识。',
    '- 会话始终归属项目和群。同一项目、同一群内的会话 ID 可以互相恢复，包括会话绑定和项目绑定产生的会话。',
    '- 禁止跨项目或跨群恢复。项目按登记的规范工作目录识别，执行子目录不改变项目归属；群必须是同一个 chat_id。',
    '- 无法确认项目和群归属的 ID 必须报错，不能因传入 `--project`、`--identity` 或某个目录就认定它属于当前项目。',
    '- `--workdir` 可以调整到本项目内的现有目录；`--identity` 可以选择原后端下的其他模型或来源。原生会话不能更换所属后端。',
    '- 恢复本轮的绑定由调用场景决定，旧调用记录不迁移；切换绑定方式不建立相互取消关系。',
    '- 同一个原生会话不能同时执行两轮，恢复失败必须显示，不得自动新建会话。',
    '',
    '## Single-level delegation',
    '',
    '- Only the main Agent may delegate work. If you are already a delegated',
    '  Agent or subagent, complete your assigned task yourself: do not delegate further.',
    '- This prohibition covers this Skill, `lodestar-agent run` / `follow-up`,',
    '  native Agent/subagent tools, and delegation through provider CLIs or HTTP APIs.',
    '- `LODESTAR_AGENT_ROLE=worker` identifies a Lodestar delegated process.',
    '  Native subagents are also delegated Agents even when they inherit a main role environment.',
    '- Return additional work requests to the main Agent. It can assign separate',
    '  tasks, continue your session, or answer your questions.',
    '',
    '## Choosing a delegation method',
    '',
    '- The main Agent chooses between native Agent/subagent capabilities and',
    '  `lodestar-agent` based on the task and available capabilities.',
    '- Both methods are allowed when calling your own model or Agent.',
    '- The Agent workflow below always uses session-bound calls. `--project` is reserved',
    '  for genuinely independent service/application clients, not Agent task execution.',
    '',
    '## Required workflow',
    '',
    '1. When using Lodestar, query the live identity catalog immediately before',
    '   every new task:',
    '',
    '```bash',
    '# desc: 查询当前可用的 Agent 身份',
    'lodestar-agent identities --json',
    '```',
    '',
    '2. Select only identities with `status: "ready"`. Never invent, cache,',
    '   substitute, or silently downgrade an identity/model/effort.',
    '3. Give the child the complete task, relevant context, authority boundaries,',
    '   expected deliverable, and verification requirements in the raw prompt.',
    '   Explicitly tell it to complete the work itself without further delegation.',
    '   Every run and follow-up also requires `--description`: a short, user-facing',
    '   single-line task summary (at most 60 characters). The card shows this line',
    '   with status; the full prompt, progress and results stay collapsed.',
    '4. For the same prompt sent to several identities, pass them to one run',
    '   with repeated `--identity`; the daemon schedules them within concurrency limits.',
    '   OpenRouter allows at most 2 delegated tasks at once across projects and models',
    '   in the same daemon; additional tasks queue. This is a local limit, not an API quota.',
    '   Wait for queued tasks instead of submitting duplicates. If rate-limited, report',
    '   the error and do not immediately retry the whole batch.',
    '5. Wait for the result. Attribute each result to its actual model and surface',
    '   failures. Child file changes are live in the same workspace.',
    '6. When the same work needs another step, review the returned content and',
    '   continue with `run --session <session-id>` plus the new input. Use as many',
    '   turns as the authorized task needs; assess completion against the overall',
    '   task and its verification requirements, not just one run ending.',
    '',
    '## Run a task',
    '',
    '```bash',
    '# desc: 把完整任务交给指定 Agent',
    "lodestar-agent run --identity '<identity-id>' --description '完成指定任务' --stdin <<'EOF'",
    '<raw task prompt written by the main Agent>',
    'EOF',
    '```',
    '',
    '### Working directory',
    '',
    'New tasks default to the main Agent working directory, even if the calling',
    'shell has changed directory. Use `--workdir <path>` to select an existing',
    'subdirectory. Relative paths are resolved from the main Agent directory;',
    'absolute paths are also accepted within that directory. Symlinks are resolved',
    'and paths outside the main directory, missing paths and files are rejected.',
    'All identities in one run use the same directory; use separate runs for different directories.',
    '',
    '```bash',
    '# desc: 在主 Agent 工作目录的子目录中执行任务',
    "lodestar-agent run --identity '<identity-id>' --description '检查应用代码' --workdir 'packages/app' --prompt 'Inspect the application and report the results.'",
    '```',
    '',
    '`run --session` and `follow-up` may select an existing directory within the same project.',
    'Without `--workdir`, reuse the recorded execution directory. A different project',
    'directory or unknown session ownership is an error. Results report `Work directory:`',
    '(JSON: `work_dir`). The HTTP API accepts `work_dir` on run/follow-up requests.',
    '',
    '## Complete one work item across multiple turns',
    '',
    'A single work item can span multiple turns in the same native Agent session.',
    'Use this for staged implementation, revisions based on feedback, or further',
    'verification of previous results. The main Agent reads each result and sends',
    'the next step; the delegated Agent still must not delegate further.',
    '',
    'Keep the returned `Session:` id (JSON: `workers[].session_id`) together with',
    'the worker output. For turn 2 and later, send that id and only the new input:',
    '',
    '```bash',
    '# desc: 用历史会话 ID 继续下一轮',
    "lodestar-agent run --session '<session-id>' --description '继续下一步任务' --stdin <<'EOF'",
    '<new input for the next turn>',
    'EOF',
    '```',
    '',
    'This resumes the provider-native conversation. Recorded identity and effort',
    'are reused when omitted. Explicit `--identity` may select another model/source in the same backend;',
    'a changed identity uses its default effort unless `--effort` is given. The run returns a new',
    '`run_id` and the same native `session_id`; repeat to continue further turns.',
    'Only ids registered to the current project and group can be resumed. The original',
    'invocation may have been session-bound or project-bound; unknown ownership is rejected.',
    'The new run belongs to the current caller; previous ownership is not transferred.',
    'Changing binding mode within the project does not join cancellation trees. Backend resume failures',
    'remain errors. Wait for that worker to exit; other workers in its run need not finish.',
    'Concurrent turns on the same provider/native session are rejected.',
    '',
    'Use `--json` with `run`, `follow-up` or `status` for structured results:',
    '`workers[].session_id` is the conversation id and `workers[].output` is the',
    'returned content. `--prompt <text>` supplies inline input instead of stdin.',
    'A parallel run returns one session id per worker; continue each separately.',
    '',
    'For example, after turn 1 implements the requested change using the run form',
    'above, continue the same work with feedback and then verification:',
    '',
    '```bash',
    '# desc: 第二轮根据上一轮结果和反馈继续修改',
    "lodestar-agent run --session '<session-id>' --description '根据反馈修改' --prompt 'Revise the previous implementation using this feedback: <specific feedback>.' --json",
    '```',
    '',
    'Read turn 2\'s result before choosing turn 3\'s input, using the same session id:',
    '',
    '```bash',
    '# desc: 第三轮验证同一项工作的最终结果',
    "lodestar-agent run --session '<session-id>' --description '验证最终结果' --prompt 'Verify the revised implementation against the original requirements and report the results and any remaining issues.' --json",
    '```',
    '',
    'These turns retain the earlier conversation; send only the new requirements,',
    'feedback or next step. Omitting `--session` starts a fresh conversation.',
    'Empty ids, unknown project/group ownership, and cross-project/group ids are rejected.',
    'The original backend then determines whether the native conversation can be resumed;',
    'failures are reported and never converted into a fresh session.',
    '',
    'If you kept the `run_id`, the existing follow-up form also resumes its worker:',
    '',
    '```bash',
    '# desc: 在同一原生 Agent 会话中继续任务',
    "lodestar-agent follow-up '<run-id>' --identity '<identity-id>' --description '完成指定任务' --stdin <<'EOF'",
    '<follow-up prompt>',
    'EOF',
    '```',
    '',
    '## Answer a child question',
    '',
    'When a run returns `Status: needs_input`, answer the exact request id. JSON',
    'keys may be the question id or the full question text:',
    '',
    '```bash',
    '# desc: 回答 Agent 的阻塞问题并继续运行',
    "lodestar-agent answer '<run-id>' --identity '<identity-id>' --request '<request-id>' --stdin <<'EOF'",
    '{"question-id":"answer"}',
    'EOF',
    '```',
    '',
    '## Boundaries',
    '',
    '- Do not invoke provider CLIs or provider HTTP APIs directly for delegation.',
    '- Never expose `LODESTAR_AGENT_CAPABILITY` in prompts, output, logs, or args.',
    '- Never read or copy daemon project-client credentials to bypass delegation restrictions.',
    '- A non-zero command exit is a real failure. Do not claim the child succeeded.',
    '- Scope the Agent task and authorized actions to the user request.',
    '',
  ].join('\n')
}

export function ensureLodestarAgentSkill(): void {
  removeManagedSkill('lodestar-consult')
  syncManagedSkill({ name: AGENT_SKILL_NAME, body: agentSkillBody() })
}
