import { removeManagedSkill, syncManagedSkill } from './managed-skills'

export const AGENT_SKILL_NAME = 'lodestar-agent'

export const DELEGATED_AGENT_INSTRUCTIONS = [
  'You are a delegated Agent working on a task assigned by the main Agent.',
  'Complete this task yourself. You must not create or invoke any further Agents or subagents.',
  'This includes Lodestar delegation, provider-native Agent/subagent tools, and delegation through CLIs or HTTP APIs.',
  'If additional Agent work is needed, report the need to the main Agent so it can assign that work.',
].join('\n')

export function agentSkillBody(): string {
  const description = 'Main Agents can delegate a task to a different configured model or Agent through Lodestar and continue the same work across multiple turns. Delegated Agents and subagents must not use this Skill or delegate further. Main-Agent self-calls use native delegation capabilities.'
  return [
    '---',
    `name: ${AGENT_SKILL_NAME}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '# lodestar-agent',
    '',
    'Use Lodestar to call the Agent represented by a selected live identity.',
    'Each identity resolves to its configured Token Source, provider Agent backend,',
    'model, and effort. The caller-supplied prompt becomes that Agent run\'s task.',
    '',
    '## Single-level delegation',
    '',
    '- Only the main Agent may delegate work. If you are already a delegated',
    '  Agent or subagent, complete your assigned task yourself: do not delegate further.',
    '- This prohibition covers this Skill, `lodestar-agent run` / `follow-up`,',
    '  native Agent/subagent tools, and delegation through provider CLIs or HTTP APIs.',
    '- `LODESTAR_AGENT_ROLE=worker` identifies a Lodestar delegated process.',
    '  Native subagents are also delegated Agents even when they inherit a main role environment.',
    '- Return additional work requests to the main Agent. It can assign separate',
    '  tasks, continue your session, or answer your questions.',
    '',
    '## Hard rule: native Agent capabilities for self-calls',
    '',
    '- For the main Agent only: when calling yourself or your own model/Agent, use your current',
    '  Agent\'s native Agent/subagent capabilities. You MUST NOT use this Skill',
    '  or the `lodestar-agent` command for self-calls.',
    '- For example, Codex calling Codex uses Codex native subagents; Claude',
    '  calling Claude uses Claude native Agent capabilities.',
    '- This does not exempt delegated Agents from the single-level rule above.',
    '- If native delegation is unavailable, report that limitation. It does not',
    '  permit routing a self-call through this Skill.',
    '',
    '## Required workflow',
    '',
    '1. For another model/Agent, query the live identity catalog immediately before',
    '   every new task:',
    '',
    '```bash',
    '# desc: 查询当前可用的 Agent 身份',
    'lodestar-agent identities --json',
    '```',
    '',
    '2. Select only identities with `status: "ready"`. Never invent, cache,',
    '   substitute, or silently downgrade an identity/model/effort.',
    '3. Give the child the complete task, relevant context, authority boundaries,',
    '   expected deliverable, and verification requirements in the raw prompt.',
    '   Explicitly tell it to complete the work itself without further delegation.',
    '4. For the same prompt sent to several other models, pass every identity to one run',
    '   with repeated `--identity`; the daemon schedules them within concurrency limits.',
    '   OpenRouter allows at most 2 delegated tasks at once across projects and models',
    '   in the same daemon; additional tasks queue. This is a local limit, not an API quota.',
    '   Wait for queued tasks instead of submitting duplicates. If rate-limited, report',
    '   the error and do not immediately retry the whole batch.',
    '5. Wait for the result. Attribute each result to its actual model and surface',
    '   failures. Child file changes are live in the same workspace.',
    '6. When the same work needs another step, review the returned content and',
    '   continue with `run --session <session-id>` plus the new input. Use as many',
    '   turns as the authorized task needs; assess completion against the overall',
    '   task and its verification requirements, not just one run ending.',
    '',
    '## Run a task',
    '',
    '```bash',
    '# desc: 把完整任务交给指定 Agent',
    "lodestar-agent run --identity '<identity-id>' --stdin <<'EOF'",
    '<raw task prompt written by the main Agent>',
    'EOF',
    '```',
    '',
    '## Complete one work item across multiple turns',
    '',
    'A single work item can span multiple turns in the same native Agent session.',
    'Use this for staged implementation, revisions based on feedback, or further',
    'verification of previous results. The main Agent reads each result and sends',
    'the next step; the delegated Agent still must not delegate further.',
    '',
    'Keep the returned `Session:` id (JSON: `workers[].session_id`) together with',
    'the worker output. For turn 2 and later, send that id and only the new input:',
    '',
    '```bash',
    '# desc: 用历史会话 ID 继续下一轮',
    "lodestar-agent run --session '<session-id>' --stdin <<'EOF'",
    '<new input for the next turn>',
    'EOF',
    '```',
    '',
    'This resumes the provider-native conversation and inherits its identity and',
    'last effort. An optional `--identity` must match the original worker;',
    '`--effort` explicitly changes the effort for this turn. The run returns a new',
    '`run_id` and the same native `session_id`; repeat to continue further turns.',
    'The session must belong to this Lodestar Session and workspace, with its',
    'delegated run history still available. Saved history supports continuation',
    'after a daemon restart. Unknown sessions, unavailable identities and native',
    'resume failures are errors. Wait for the current run to finish before resuming;',
    'concurrent turns on the same native session are rejected.',
    '',
    'Use `--json` with `run`, `follow-up` or `status` for structured results:',
    '`workers[].session_id` is the conversation id and `workers[].output` is the',
    'returned content. `--prompt <text>` supplies inline input instead of stdin.',
    'A parallel run returns one session id per worker; continue each separately.',
    '',
    'For example, after turn 1 implements the requested change using the run form',
    'above, continue the same work with feedback and then verification:',
    '',
    '```bash',
    '# desc: 第二轮根据上一轮结果和反馈继续修改',
    "lodestar-agent run --session '<session-id>' --prompt 'Revise the previous implementation using this feedback: <specific feedback>.' --json",
    '```',
    '',
    'Read turn 2\'s result before choosing turn 3\'s input, using the same session id:',
    '',
    '```bash',
    '# desc: 第三轮验证同一项工作的最终结果',
    "lodestar-agent run --session '<session-id>' --prompt 'Verify the revised implementation against the original requirements and report the results and any remaining issues.' --json",
    '```',
    '',
    'These turns retain the earlier conversation; send only the new requirements,',
    'feedback or next step. Omitting `--session` starts a fresh conversation.',
    'An empty, unknown or out-of-scope session id is rejected before execution;',
    'native resume failures are reported and never converted into a fresh session.',
    '',
    'If you kept the `run_id`, the existing follow-up form also resumes its worker:',
    '',
    '```bash',
    '# desc: 在同一原生 Agent 会话中继续任务',
    "lodestar-agent follow-up '<run-id>' --identity '<identity-id>' --stdin <<'EOF'",
    '<follow-up prompt>',
    'EOF',
    '```',
    '',
    '## Answer a child question',
    '',
    'When a run returns `Status: needs_input`, answer the exact request id. JSON',
    'keys may be the question id or the full question text:',
    '',
    '```bash',
    '# desc: 回答 Agent 的阻塞问题并继续运行',
    "lodestar-agent answer '<run-id>' --identity '<identity-id>' --request '<request-id>' --stdin <<'EOF'",
    '{"question-id":"answer"}',
    'EOF',
    '```',
    '',
    '## Boundaries',
    '',
    '- Do not invoke provider CLIs or provider HTTP APIs directly for delegation.',
    '- Never expose `LODESTAR_AGENT_CAPABILITY` in prompts, output, logs, or args.',
    '- A non-zero command exit is a real failure. Do not claim the child succeeded.',
    '- Scope the Agent task and authorized actions to the user request.',
    '',
  ].join('\n')
}

export function ensureLodestarAgentSkill(): void {
  removeManagedSkill('lodestar-consult')
  syncManagedSkill({ name: AGENT_SKILL_NAME, body: agentSkillBody() })
}
