import { removeManagedSkill, syncManagedSkill } from './managed-skills'

export const AGENT_SKILL_NAME = 'lodestar-agent'

export const DELEGATED_AGENT_INSTRUCTIONS = [
  'You are a delegated Agent working on a task assigned by the main Agent.',
  'Complete this task yourself. You must not create or invoke any further Agents or subagents.',
  'This includes Lodestar delegation, provider-native Agent/subagent tools, and delegation through CLIs or HTTP APIs.',
  'If additional Agent work is needed, report the need to the main Agent so it can assign that work.',
].join('\n')

export function agentSkillBody(): string {
  const description = 'Main Agents can delegate a task to a different configured model or Agent through Lodestar. Delegated Agents and subagents must not use this Skill or delegate further. Main-Agent self-calls use native delegation capabilities.'
  return [
    '---',
    `name: ${AGENT_SKILL_NAME}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '# lodestar-agent',
    '',
    'Use Lodestar to call the Agent represented by a selected live identity.',
    'Each identity resolves to its configured Token Source, provider Agent backend,',
    'model, and effort. The caller-supplied prompt becomes that Agent run\'s task.',
    '',
    '## Single-level delegation',
    '',
    '- Only the main Agent may delegate work. If you are already a delegated',
    '  Agent or subagent, complete your assigned task yourself: do not delegate further.',
    '- This prohibition covers this Skill, `lodestar-agent run` / `follow-up`,',
    '  native Agent/subagent tools, and delegation through provider CLIs or HTTP APIs.',
    '- `LODESTAR_AGENT_ROLE=worker` identifies a Lodestar delegated process.',
    '  Native subagents are also delegated Agents even when they inherit a main role environment.',
    '- Return additional work requests to the main Agent. It can assign separate',
    '  tasks, continue your session, or answer your questions.',
    '',
    '## Hard rule: native Agent capabilities for self-calls',
    '',
    '- For the main Agent only: when calling yourself or your own model/Agent, use your current',
    '  Agent\'s native Agent/subagent capabilities. You MUST NOT use this Skill',
    '  or the `lodestar-agent` command for self-calls.',
    '- For example, Codex calling Codex uses Codex native subagents; Claude',
    '  calling Claude uses Claude native Agent capabilities.',
    '- This does not exempt delegated Agents from the single-level rule above.',
    '- If native delegation is unavailable, report that limitation. It does not',
    '  permit routing a self-call through this Skill.',
    '',
    '## Required workflow',
    '',
    '1. For another model/Agent, query the live identity catalog immediately before',
    '   every new task:',
    '',
    '```bash',
    '# desc: 查询当前可用的 Agent 身份',
    'lodestar-agent identities --json',
    '```',
    '',
    '2. Select only identities with `status: "ready"`. Never invent, cache,',
    '   substitute, or silently downgrade an identity/model/effort.',
    '3. Give the child the complete task, relevant context, authority boundaries,',
    '   expected deliverable, and verification requirements in the raw prompt.',
    '   Explicitly tell it to complete the work itself without further delegation.',
    '4. For the same prompt sent to several other models, pass every identity to one run',
    '   with repeated `--identity`; the daemon schedules them within concurrency limits.',
    '   OpenRouter allows at most 2 delegated tasks at once across projects and models',
    '   in the same daemon; additional tasks queue. This is a local limit, not an API quota.',
    '   Wait for queued tasks instead of submitting duplicates. If rate-limited, report',
    '   the error and do not immediately retry the whole batch.',
    '5. Wait for the result. Attribute each result to its actual model and surface',
    '   failures. Child file changes are live in the same workspace.',
    '',
    '## Run a task',
    '',
    '```bash',
    '# desc: 把完整任务交给指定 Agent',
    "lodestar-agent run --identity '<identity-id>' --stdin <<'EOF'",
    '<raw task prompt written by the main Agent>',
    'EOF',
    '```',
    '',
    '## Continue the same native Agent session',
    '',
    '```bash',
    '# desc: 在同一原生 Agent 会话中继续任务',
    "lodestar-agent follow-up '<run-id>' --identity '<identity-id>' --stdin <<'EOF'",
    '<follow-up prompt>',
    'EOF',
    '```',
    '',
    '## Answer a child question',
    '',
    'When a run returns `Status: needs_input`, answer the exact request id. JSON',
    'keys may be the question id or the full question text:',
    '',
    '```bash',
    '# desc: 回答 Agent 的阻塞问题并继续运行',
    "lodestar-agent answer '<run-id>' --identity '<identity-id>' --request '<request-id>' --stdin <<'EOF'",
    '{"question-id":"answer"}',
    'EOF',
    '```',
    '',
    '## Boundaries',
    '',
    '- Do not invoke provider CLIs or provider HTTP APIs directly for delegation.',
    '- Never expose `LODESTAR_AGENT_CAPABILITY` in prompts, output, logs, or args.',
    '- A non-zero command exit is a real failure. Do not claim the child succeeded.',
    '- Scope the Agent task and authorized actions to the user request.',
    '',
  ].join('\n')
}

export function ensureLodestarAgentSkill(): void {
  removeManagedSkill('lodestar-consult')
  syncManagedSkill({ name: AGENT_SKILL_NAME, body: agentSkillBody() })
}
