import { afterEach, describe, expect, spyOn, test } from 'bun:test'
import * as fs from 'node:fs'
import * as stateStore from './state-store'
import { mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync, statSync, symlinkSync, unlinkSync, writeFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { CodexAccounts, reserveCodexLogin, isCodexLoginPending } from './codex-accounts'

const roots: string[] = []
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }) })
function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'codex-account-test-')); roots.push(root)
  const home = join(root, 'native'); mkdirSync(home)
  writeFileSync(join(home, 'config.toml'), 'model = "test-model"\n')
  writeFileSync(join(home, 'auth.json'), '{"native":"must-not-change"}')
  return new CodexAccounts(home, join(root, 'accounts'), join(root, 'accounts.json'))
}

describe('Codex native and named accounts', () => {
  test('each native login invalidates its cache revision without touching credentials or other accounts', () => {
    const accounts = fixture()
    const named = accounts.ensure('work')
    const nativeRevision = accounts.revision('default')
    const namedRevision = accounts.revision(named.id)
    const saved = readFileSync(accounts.stateFile, 'utf8')
    accounts.recordLogin('default', { email: 'first@example.test', planType: 'plus' })
    const loggedIn = accounts.revision('default')
    expect(loggedIn).not.toBe(nativeRevision)
    expect(accounts.revision(named.id)).toBe(namedRevision)
    accounts.recordLogin('default', { email: 'second@example.test', planType: 'pro' })
    expect(accounts.revision('default')).not.toBe(loggedIn)
    expect(readFileSync(accounts.stateFile, 'utf8')).toBe(saved)
    expect(readFileSync(join(accounts.defaultHome, 'auth.json'), 'utf8')).toBe('{"native":"must-not-change"}')
  })

  test('deleting a named account removes its credentials and selections while preserving shared data and other accounts', () => {
    const accounts = fixture()
    const removed = accounts.ensure('不要了')
    const kept = accounts.ensure('保留')
    const home = accounts.prepareHome(removed.id)
    const keptHome = accounts.prepareHome(kept.id)
    writeFileSync(join(home, 'auth.json'), 'removed credentials')
    writeFileSync(join(keptHome, 'auth.json'), 'kept credentials')
    writeFileSync(join(home, 'sessions', 'history.jsonl'), 'shared history')
    writeFileSync(join(home, 'thread-writer-locks', 'thread.lock'), 'shared lock')
    writeFileSync(join(accounts.defaultHome, 'state.sqlite'), 'shared database')
    accounts.select('one', removed.id)
    accounts.select('__proto__', removed.id)
    accounts.select('two', kept.id)
    accounts.select('native', 'default')

    expect(accounts.remove(removed.id)).toEqual({ account: removed, clearedSelections: 2 })
    expect(existsSync(home)).toBe(false)
    expect(readFileSync(join(keptHome, 'auth.json'), 'utf8')).toBe('kept credentials')
    expect(readFileSync(join(keptHome, 'sessions', 'history.jsonl'), 'utf8')).toBe('shared history')
    expect(readFileSync(join(keptHome, 'thread-writer-locks', 'thread.lock'), 'utf8')).toBe('shared lock')
    expect(readFileSync(join(accounts.defaultHome, 'state.sqlite'), 'utf8')).toBe('shared database')
    expect(readFileSync(join(accounts.defaultHome, 'auth.json'), 'utf8')).toBe('{"native":"must-not-change"}')
    expect(readFileSync(join(accounts.defaultHome, 'config.toml'), 'utf8')).toBe('model = "test-model"\n')
    const reloaded = new CodexAccounts(accounts.defaultHome, accounts.root, accounts.stateFile)
    expect(reloaded.list().map(a => a.id)).toEqual(['default', kept.id])
    expect(reloaded.preferred('one')).toBeNull()
    expect(reloaded.preferred('__proto__')).toBeNull()
    expect(reloaded.preferred('two')).toBe(kept.id)
    expect(reloaded.preferred('native')).toBe('default')
    expect(() => reloaded.env(removed.id, {})).toThrow('不存在')
    expect(reloaded.ensure(removed.name).id).not.toBe(removed.id)
  })
  test('deletion also removes records left by a login that never created a home', () => {
    const accounts = fixture()
    const account = accounts.ensure('未完成登录')
    expect(existsSync(accounts.home(account.id))).toBe(false)
    accounts.remove(account.id)
    expect(accounts.list().map(a => a.id)).toEqual(['default'])
    expect(() => accounts.remove(account.id)).toThrow('不存在')
    expect(() => accounts.remove('default')).toThrow('默认账号')
    expect(existsSync(join(accounts.defaultHome, 'auth.json'))).toBe(true)
  })
  test('deletion refuses directory aliases and homes containing the native account', () => {
    const accounts = fixture()
    const account = accounts.ensure('unsafe')
    mkdirSync(accounts.root)
    const home = accounts.home(account.id)
    symlinkSync(accounts.defaultHome, home, 'dir')
    expect(() => accounts.remove(account.id)).toThrow('不是独立目录')
    unlinkSync(home)
    mkdirSync(home)
    const same = new CodexAccounts(home, accounts.root, accounts.stateFile)
    expect(() => same.remove(account.id)).toThrow('包含默认认证目录')
    const nested = join(home, 'native'); mkdirSync(nested)
    const inside = new CodexAccounts(nested, accounts.root, accounts.stateFile)
    expect(() => inside.remove(account.id)).toThrow('包含默认认证目录')
    expect(accounts.get(account.id)).toEqual(account)
    expect(readFileSync(join(accounts.defaultHome, 'auth.json'), 'utf8')).toBe('{"native":"must-not-change"}')
  })
  test('filesystem and registry failures stay visible and leave a record that can be retried', () => {
    const accounts = fixture()
    const account = accounts.ensure('retry')
    const home = accounts.prepareHome(account.id)
    writeFileSync(join(home, 'auth.json'), 'private credentials')
    accounts.select('one', account.id)
    const remove = spyOn(fs, 'rmSync').mockImplementation(() => { throw new Error('EACCES test') })
    try {
      expect(() => accounts.remove(account.id)).toThrow('EACCES test')
      expect(readFileSync(join(home, 'auth.json'), 'utf8')).toBe('private credentials')
      expect(accounts.preferred('one')).toBe(account.id)
    } finally { remove.mockRestore() }
    const write = spyOn(stateStore, 'writeJsonStateAtomic').mockImplementation(() => { throw new Error('ENOSPC test') })
    try {
      expect(() => accounts.remove(account.id)).toThrow('账号文件已移除，但账号记录保存失败')
      expect(existsSync(home)).toBe(false)
      expect(accounts.get(account.id)).toEqual(account)
      expect(accounts.preferred('one')).toBe(account.id)
    } finally { write.mockRestore() }
    accounts.remove(account.id)
    expect(accounts.preferred('one')).toBeNull()
    expect(accounts.list().map(a => a.id)).toEqual(['default'])
  })
  test('named account aliases cannot redirect credential writes into the native account', () => {
    const accounts = fixture()
    const named = accounts.ensure('alias')
    mkdirSync(accounts.root)
    symlinkSync(accounts.defaultHome, accounts.home(named.id), 'dir')
    expect(() => accounts.prepareHome(named.id)).toThrow('不能是软链接')
    unlinkSync(accounts.home(named.id))
    const home = accounts.prepareHome(named.id)
    symlinkSync(join(accounts.defaultHome, 'auth.json'), join(home, 'auth.json'))
    expect(() => accounts.prepareHome(named.id)).toThrow('必须为独立文件')
    expect(readFileSync(join(accounts.defaultHome, 'auth.json'), 'utf8')).toBe('{"native":"must-not-change"}')
  })
  test('credential writes exclude other launches until their exact login lease is released', () => {
    const accounts = fixture()
    const account = accounts.ensure('login lock')
    const release = reserveCodexLogin(account.id)
    try {
      expect(isCodexLoginPending(account.id)).toBe(true)
      expect(() => reserveCodexLogin(account.id)).toThrow('已有登录任务')
      expect(() => accounts.env(account.id, {})).toThrow('正在登录')
      expect(() => accounts.remove(account.id)).toThrow('正在登录')
      expect(accounts.env(account.id, {}, true, true).CODEX_HOME).toBe(accounts.home(account.id))
      expect(accounts.env('default', {}).CODEX_HOME).toBe(accounts.defaultHome)
    } finally { release() }
    expect(isCodexLoginPending(account.id)).toBe(false)
    expect(accounts.env(account.id, {}).CODEX_HOME).toBe(accounts.home(account.id))
  })
  test('default is the native home; named logins never copy or replace native auth', () => {
    const accounts = fixture()
    expect(accounts.find().id).toBe('default')
    expect(accounts.find('默认').id).toBe('default')
    const named = accounts.ensure('工作 订阅')
    const home = accounts.prepareHome(named.id)
    expect(home).not.toBe(accounts.defaultHome)
    expect(existsSync(join(home, 'auth.json'))).toBe(false)
    expect(readFileSync(join(accounts.defaultHome, 'auth.json'), 'utf8')).toBe('{"native":"must-not-change"}')
    expect(realpathSync(join(home, 'sessions'))).toBe(realpathSync(join(accounts.defaultHome, 'sessions')))
    expect(realpathSync(join(home, 'thread-writer-locks'))).toBe(realpathSync(join(accounts.defaultHome, 'thread-writer-locks')))
    expect(realpathSync(join(home, 'config.toml'))).toBe(join(accounts.defaultHome, 'config.toml'))
    expect(existsSync(join(home, 'models_cache.json'))).toBe(false)
    if (process.platform !== 'win32') expect(statSync(home).mode & 0o777).toBe(0o700)
  })

  test('name lookup is normalized and per-group selections survive reconstruction', () => {
    const accounts = fixture()
    const a = accounts.ensure('Work')
    expect(accounts.ensure('work').id).toBe(a.id)
    expect(accounts.find(' WORK ').id).toBe(a.id)
    accounts.select('one', a.id)
    const reloaded = new CodexAccounts(accounts.defaultHome, accounts.root, accounts.stateFile)
    expect(reloaded.selected('one')).toBe(a.id)
    expect(reloaded.selected('two')).toBe('default')
    expect(reloaded.selected('constructor')).toBe('default')
    reloaded.select('__proto__', a.id)
    expect(reloaded.selected('__proto__')).toBe(a.id)
    expect(reloaded.home('default')).toBe(accounts.defaultHome)
    expect(() => reloaded.select('one', 'missing')).toThrow('不存在')
    expect(reloaded.selected('one')).toBe(a.id)
    for (const name of ['../escape', 'a\\b', 'a\nb', '..']) expect(() => accounts.ensure(name)).toThrow()
  })

  test('conflicting shared files and corrupt state fail visibly', () => {
    const accounts = fixture()
    const named = accounts.ensure('work')
    const home = accounts.prepareHome(named.id)
    unlinkSync(join(home, 'config.toml'))
    writeFileSync(join(home, 'config.toml'), 'diverged = true')
    expect(() => accounts.prepareHome(named.id)).toThrow('已被替换')
    writeFileSync(accounts.stateFile, '{"version":9}')
    expect(() => accounts.list()).toThrow('格式无效')
  })

  test('named launches require their own ChatGPT file credentials and shared database directory', () => {
    const accounts = fixture()
    const named = accounts.ensure('work')
    const env = accounts.env(named.id, { CODEX_HOME: '/foreign', CODEX_ACCESS_TOKEN: 'foreign-token',
      OPENAI_API_KEY: 'foreign-key', OPENAI_IDENTITY_TOKEN_FILE: '/foreign-token', PATH: '/bin' })
    expect(env.CODEX_HOME).toBe(accounts.home(named.id))
    // 调用方没有在 base 中传入数据库目录，不能读取测试宿主的全局环境。
    expect(env.CODEX_SQLITE_HOME).toBe(accounts.defaultHome)
    expect(env.PATH).toBe('/bin')
    expect(env.CODEX_ACCESS_TOKEN).toBeUndefined()
    expect(env.OPENAI_API_KEY).toBeUndefined()
    expect(env.OPENAI_IDENTITY_TOKEN_FILE).toBeUndefined()
    expect(accounts.env(named.id, { CODEX_SQLITE_HOME: '/shared/custom-state' }).CODEX_SQLITE_HOME).toBe('/shared/custom-state')
    expect(accounts.cliArgs(named.id)).toContain('cli_auth_credentials_store="file"')
    expect(accounts.cliArgs('default')).toEqual([])
    expect(accounts.env('default', { CODEX_ACCESS_TOKEN: 'native-token' }).CODEX_ACCESS_TOKEN).toBe('native-token')
  })

  test('quota deduplication uses stable user/workspace identity, never a token or remark', () => {
    const accounts = fixture()
    const named = accounts.ensure('same login')
    const home = accounts.prepareHome(named.id)
    const token = (sub: string) => `header.${Buffer.from(JSON.stringify({ sub })).toString('base64url')}.signature`
    const auth = { tokens: { account_id: 'workspace-test', id_token: token('user-test'), access_token: 'secret-one' } }
    writeFileSync(join(accounts.defaultHome, 'auth.json'), JSON.stringify(auth))
    writeFileSync(join(home, 'auth.json'), JSON.stringify({ tokens: { ...auth.tokens, access_token: 'secret-two' } }))
    expect(accounts.fingerprint('default')).toBe(accounts.fingerprint(named.id))
    expect(accounts.fingerprint('default')).not.toContain('secret')
    writeFileSync(join(home, 'auth.json'), JSON.stringify({ tokens: { ...auth.tokens, id_token: token('different-user') } }))
    expect(accounts.fingerprint('default')).not.toBe(accounts.fingerprint(named.id))
  })
})
